backend:
  name: git-gateway
  branch: main

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "base.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta Description", name: "description", widget: "text"}
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Description", name: "heroDescription", widget: "text"}
          - {label: "Hero CTA Text", name: "heroCtaText", widget: "string"}
          - {label: "Hero CTA Link", name: "heroCtaLink", widget: "string"}
          - {label: "Services Title", name: "servicesTitle", widget: "string"}
          - {label: "Services Description", name: "servicesDescription", widget: "text"}
          - {label: "Services", name: "services", widget: "list", fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}}

  - name: "ru_pages"
    label: "Russian Pages"
    files:
      - file: "src/ru/index.html"
        label: "Russian Home Page"
        name: "ru_home"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "base.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta Description", name: "description", widget: "text"}
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Description", name: "heroDescription", widget: "text"}
          - {label: "Hero CTA Text", name: "heroCtaText", widget: "string"}
          - {label: "Hero CTA Link", name: "heroCtaLink", widget: "string"}
          - {label: "Services Title", name: "servicesTitle", widget: "string"}
          - {label: "Services Description", name: "servicesDescription", widget: "text"}
          - {label: "Services", name: "services", widget: "list", fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}}

  - name: "portfolio"
    label: "Portfolio"
    folder: "src/_data/portfolio"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}

  - name: "ru_portfolio"
    label: "Russian Portfolio"
    folder: "src/_data/ru_portfolio"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Link", name: "link", widget: "string"} 